### ISSUE TITLE
Messaging feature between user and randomly connected user

### ISSUE THREAD

**Issue by jttran28** [MSUiOSGroup5/MSU-Student-Link#5]
**Reference**
- [Unit 6 Assignment](https://courses.codepath.org/courses/ios_university/unit/6#!assignment)
- [ ] Create inbox screen
- [ ] Create private messaging screen
- [ ] Implement messaging feature between user and other user

**Comment by guptaru1** [comment]
Messaging feature implemented but still needs to work with the other user
